--------MetaMKT.SALES0 B
SELECT *
FROM RPT_MARKETING_SALES_1 rms ;
-----------------OUTLET.PBI.DET
CREATE OR REPLACE VIEW OUTLET_PBI_DET_ARIS AS
SELECT
c.OUTLET_ID,
c.OUTLET_PBI,
c.USER_UPDATE,
c.USER_DATE
FROM OUTLET_PBI_DET c
INNER JOIN OUTLET a
ON c.OUTLET_ID = a.OUTLET_ID
INNER JOIN OUTLET_PBI b
ON c.OUTLET_PBI = b.OUTLET_PBI
WHERE C.OUTLET_ID LIKE '%%';
----------------Sales0
SELECT *
FROM SALES1_ARIS SA
JOIN OUTLET_PBI_DET_ARIS OB ON SA.OUTLET_ID = OB.OUTLET_ID;

-----------SALE0 FINAL
SELECT 
    A.TGL,
    O.OUTLET_PBI,
    A.J_PATIENT + A.R_PATIENT AS PATIENT,
    A.J_TEST + A.R_TEST AS TEST,
    A.BRUTO,
    A.DISKON,
    A.NETTO,
    A.RETUR,
    A.NETTO - A.RETUR  AS TOTAL
FROM 
    SALES1_ARIS A
LEFT JOIN 
    OUTLET_PBI_DET O ON A.OUTLET_ID = O.OUTLET_ID
WHERE 
    TRUNC(A.TGL) >= TRUNC(SYSDATE-120);

----------SALES0 FINAL REVISI
   SELECT 
    A.TGL,
    CASE WHEN O.OUTLET_PBI is NULL THEN 'NULL' ELSE O.OUTLET_PBI END AS OUTLET_PBI,
    SUM(A.J_PATIENT + A.R_PATIENT) AS PATIENT,
    SUM(A.J_TEST + A.R_TEST) AS TEST,
    SUM(A.BRUTO) AS BRUTO,
    SUM(A.DISKON) AS DISKON,
    SUM(A.NETTO) AS NETTO,
    SUM(A.RETUR) AS RETUR,
    SUM(A.NETTO - A.RETUR)  AS TOTAL
FROM 
    SALES1_ARIS A
LEFT JOIN 
    OUTLET_PBI_DET O ON A.OUTLET_ID = O.OUTLET_ID
WHERE 
    TRUNC(A.TGL) >= TRUNC(SYSDATE-120)
GROUP BY A.TGL, OUTLET_PBI;