  SELECT A.OUTLET_PBI, A.TGL, A.TAHUN, A.BULAN,
    DECODE(A.workday, 
       '0',0,B.TARGET_HARIAN) TARGET,
    DECODE(A.workday,'0',0,C.TARGET_HARIAN) TARGET_VISIT
FROM (
SELECT A.OUTLET_PBI, B.TGL,B.DAY,B.TAHUN, B.BULAN, B.WORKDAY
FROM OUTLET_PBI A, WORKDAY B) A, MTARGETMONTH B, MTARGETMONTH_VISIT C
WHERE A.OUTLET_PBI= B.OUTLET_PBI(+)
    AND A.TAHUN = B.TAHUN(+)
    AND A.BULAN = B.BULAN(+)
    AND A.OUTLET_PBI = C.OUTLET_PBI(+)
    AND A.TAHUN = C.TAHUN(+)
    AND A.BULAN = C.BULAN(+)
ORDER BY OUTLET_PBI, TGL;