SELECT A.OUTLET_PBI, O.NAME, R.NAME REGION, A.TGL, A.TAHUN, A.BULAN, A.TARGET, A.TARGET_VISIT,
    B.PATIENT, B.TEST, B.BRUTO, B.DISKON, B.NETTO, B.RETUR, B.TOTAL,
    SUBSTR(A.TAHUN+10001,2,4) TAHUN1,SUBSTR(A.TAHUN+10002,2,4) TAHUN2,
    SUBSTR(A.TAHUN+10003,2,4) TAHUN3,SUBSTR(A.TAHUN+10004,2,4) TAHUN4,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')
        THEN B.TOTAL ELSE 0 END REV_TH_0,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-1
        THEN B.TOTAL ELSE 0 END REV_TH_1,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-2
        THEN B.TOTAL ELSE 0 END REV_TH_2,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-3
        THEN B.TOTAL ELSE 0 END REV_TH_3,
     CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-4
        THEN B.TOTAL ELSE 0 END REV_TH_4,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')
        THEN B.PATIENT ELSE 0 END VISIT_TH_0,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-1
        THEN B.PATIENT ELSE 0 END VISIT_TH_1,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-2
        THEN B.PATIENT ELSE 0 END VISIT_TH_2,
    CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-3
        THEN B.PATIENT ELSE 0 END VISIT_TH_3,
     CASE 
        WHEN TO_CHAR(A.TGL,'DDMMYY') = TO_CHAR(A.TGL,'DDMM')||TO_CHAR(SYSDATE,'YY')-4
        THEN B.PATIENT ELSE 0 END VISIT_TH_4,
    CASE 
    WHEN TO_CHAR(A.TGL,'MMDD') <= TO_CHAR(SYSDATE,'MMDD') THEN 'UNTIL DATE' ELSE 'AFTER DATE' END KODE
FROM MTARGET_ARIS A, SALES0_ARIS B, OUTLET_PBI O, TBL_REGION_ERP R
WHERE A.OUTLET_PBI = B.OUTLET_PBI(+)
    AND A.TGL = B.TGL(+)
    AND A.OUTLET_PBI = O.OUTLET_PBI(+)
    AND O.REGION_ID = R.PBI_REGION_ID(+)
    AND A.TAHUN > '2016'
    AND ROWNUM <= 10000;